import { sidebar } from "vuepress-theme-hope";

export const zhSidebar = sidebar({
    "/Overview/": [
      "",
      "TechnicalArchitecture",
      "Changelog",
    ],
    "/QuickStart/": [
      // "",
      "Environment",
      "Register",
      "BasicCommands",
      "Contribute",
      "HowToAsk",
    ],
    "/SurvivalGuide/": [
        {
            text: "生存服介绍",
            icon: "material-icon-theme:minecraft",
            link: "/SurvivalGuide/SurvivalServer/",
            exact: true,
            prefix: "/SurvivalGuide/SurvivalServer/",
            collapsible: false,
            expanded: true,
            children: [
                "Survival-Main",
                "Survival-Industry",
                "Survival-Resource"
            ],
        },
        {
            text: "经济系统",
            icon: "noto:bank",
            link: "/SurvivalGuide/EconomicSystem/",
            exact: true,
            prefix: "/SurvivalGuide/EconomicSystem/",
            collapsible: false,
            expanded: true,
            children: [
                "MakeMoney",
                "Residence",
                "Shop"
            ],
        },
        {
            text: "常见问题",
            icon: "fluent-color:notebook-question-mark-20",
            link: "/SurvivalGuide/Support/",
            exact: true,
            prefix: "/SurvivalGuide/Support/",
            collapsible: false,
            expanded: true,
            children: [
                "Service",
                "Technical",
            ],
        },
    ],

    "/PluginIntroduction/": [
      "",
      {
        text: "自研插件",
        icon: "mdi:hammer-wrench",
        prefix: "/PluginIntroduction/",
        collapsible: false,
        expanded: true,
        children: [
          "ServerTeleport",
          "RandomTeleport",
          "GlobalChat",
          "DeathChest",
        ],
      },
      {
        text: "开源插件",
        icon: "mdi:open-source-initiative",
        prefix: "/PluginIntroduction/",
        collapsible: false,
        expanded: true,
        children: [
          "AdvancedPortals",
          "AngelChest",
          "Bluemap",
          "CoreProtect",
          "DecentHolograms",
          "Dynmap",
          "FastAsyncWorldEdit",
          "Gist",
          "LeavesFakePlayer",
          "LuckPerms",
          "MultiverseCore",
          "PlotSquared",
          "SimpleVoiceChat",
        ],
      },
    ],
    "/ServerIntroduction/": "structure",
    "/Chronicle/": "structure",

    "/PlayerProfiles/": [
      {
        text: "玩家档案",
        icon: "fluent-emoji:busts-in-silhouette",
        link: "/PlayerProfiles/",
        exact: true,
      },
      {
        text: "A – D",
        icon: "mdi:alpha-a-circle",
        prefix: "/PlayerProfiles/",
        collapsible: true,
        children: [
          "ACertainPlayer",
          "ADCa",
          "Altair",
          "Aplence",
          "ARKsealin",
          "Baishui2333",
          "mc_bookman",
          "CCapsule",
          "Dai_mao",
          "Daytona_q",
        ],
      },
      {
        text: "E – G",
        icon: "mdi:alpha-e-circle",
        prefix: "/PlayerProfiles/",
        collapsible: true,
        children: ["Evalyn", "FRIEDparrot"],
      },
      {
        text: "H – K",
        icon: "mdi:alpha-h-circle",
        prefix: "/PlayerProfiles/",
        collapsible: true,
        children: [
          "Hakumei",
          "Hoshizorarin",
          "Irving_Dragon",
          "JingKaiNing",
          "July",
          "KCN",
          "Kuake",
        ],
      },
      {
        text: "L – N",
        icon: "mdi:alpha-l-circle",
        prefix: "/PlayerProfiles/",
        collapsible: true,
        children: [
          "LLLLL",
          "lyyyyds",
          "maple",
          "mark_kram",
          "MikuMikuMi",
          "Milk_Am",
          "Minecraft",
          "MMRlove",
          "Monikard",
        ],
      },
      {
        text: "O – Q",
        icon: "mdi:alpha-o-circle",
        prefix: "/PlayerProfiles/",
        collapsible: true,
        children: [
          "OldChuaN_",
          "Kurumisama",
          "Orange_Chengjun",
          "panbaiyuan",
          "PrettyReol",
          "poiuy",
        ],
      },
      {
        text: "R – T",
        icon: "mdi:alpha-r-circle",
        prefix: "/PlayerProfiles/",
        collapsible: true,
        children: [
          "Rinryrethoic",
          "rit",
          "sakura",
          "sanae",
          "shenjack",
          "Sirius0v0",
          "SUPER2FH",
          "TeachingFeelings",
          "threecircles",
        ],
      },
      {
        text: "U – W",
        icon: "mdi:alpha-u-circle",
        prefix: "/PlayerProfiles/",
        collapsible: true,
        children: ["Umitsuki", "westddd720", "wreg"],
      },
      {
        text: "X – Z",
        icon: "mdi:alpha-x-circle",
        prefix: "/PlayerProfiles/",
        collapsible: true,
        children: [
          "xiaoxiaolu",
          "Xuanzha",
          "YiMeng",
          "yuguidahai",
          "ZhishuiDuqiu",
        ],
      },
    ],

});
